### ISSUE TITLE
Trouble building Kukkii

### ISSUE THREAD

**Issue by AyanamiRei1** [IcySon55/Kuriimu#390]
I'm just getting a bunch of "Settings" does not contain a definition errors and a bunch of The Variable is not used errors as well.

This is with the newest version of Kukkii

**Comment by onepiecefreak3** [comment]
How about you follow the issue template?

**Comment by AyanamiRei1** [comment]
Issue: [bug report] 
Type: [text | image | archive]

More details:
I'm just getting a bunch of "Settings" does not contain a definition errors and a bunch of The Variable is not used errors as well.

![attbn1s](https://user-images.githubusercontent.com/25233407/34779423-0d0acb70-f618-11e7-9c79-c62403882111.png)
![k688wsa](https://user-images.githubusercontent.com/25233407/34779431-11e0cf8c-f618-11e7-9b59-92be6ab18bc5.png)
![9uqixmi](https://user-images.githubusercontent.com/25233407/34779437-17dd0874-f618-11e7-9017-ace712b349c1.png)

**Comment by IcySon55** [comment]
Do you have Git for Windows installed? It is required for the time being, be sure that when you install it that the installer includes git in your PATH so that VS can launch it properly.

**Comment by AyanamiRei1** [comment]
I didn't I do now so what do I gotta do?

**Comment by IcySon55** [comment]
Install it and make sure that it gets put in your PATH environment variable. Maybe you need to restart for it to take effect? That's it.

**Comment by IcySon55** [comment]
@AyanamiRei1 Did you get it building yet?

**Comment by onepiecefreak3** [comment]
So is this problem solved now or something? Can this issue be closed?

**Comment by AyanamiRei1** [comment]
No it isn't solved I'm just confused on what to do I've never had to use git when building stuff ever.

**Comment by onepiecefreak3** [comment]
Well that's just a dependency for this project, there are other projects with other dependencies too. And our dependency for now is git. Therefore do as Icy said and install it and add it to your PATH environment (that can be done when installing git) and restart your PC. So why are you confused in what to do?

**Comment by gudenau** [comment]
I 100% have git.exe in my path and the build errors appear to be caused by a lack of fields in Kukkii::Properties::Settings.Default.

Investigating more.

**Comment by gudenau** [comment]
I added the missing setting values and it builds.

**Comment by onepiecefreak3** [comment]
I just redownloaded the whole source code and compiled EVERYTHING without an error. Not even the missing fields were mentioned. The applications could start, every setting was there as expected and the plugins worked.
So even if the fields are missing for you, from the current source the application is fully buildable without changes.

**Comment by IcySon55** [comment]
What onepiecefreak said. I've updated to the latest changes and there are no missing Settings or any other issues. You guys might want to make fresh forks and build from there.

**Comment by gudenau** [comment]
Here's what I did:
git clone https://github.com/IcySon55/Kuriimu.git
Open VS project.
Update project.
Batch build.
Select all.
Build.

**Comment by onepiecefreak3** [comment]
Either way I pushed a change to the settings. Now it should also build. Best of luck.

**Comment by onepiecefreak3** [comment]
Try again, and maybe we can close this issue then. Otherwise there shouldn't be any more errors application wise to blocking the build process.

**Comment by gudenau** [comment]
It appears to work now,

**Comment by onepiecefreak3** [comment]
Then I close this issue.
